from __future__ import annotations

from typing import Protocol


class DashboardQueryService(Protocol):
    def metrics(self) -> list[dict]:
        ...

    def get_dashboard_metrics(self) -> list[dict]:
        ...

    def get_cybersecurity_evaluation_metrics(self) -> list[dict]:
        ...

    def list_assets(self) -> list[dict]:
        ...

    def list_discovered_devices(self) -> list[dict]:
        ...

    def scan_network(self) -> list[dict]:
        ...

    def get_devices(self) -> list[dict]:
        ...

    def get_alerts(self) -> list[dict]:
        ...

    def get_incidents(self) -> list[dict]:
        ...

    def get_connections(self) -> list[dict]:
        ...

    def get_dns_logs(self) -> list[dict]:
        ...

    def get_traffic_logs(self) -> list[dict]:
        ...

    def get_debug_status(self) -> dict:
        ...

    def run_validation_test(self, test_key: str) -> dict:
        ...

    def generate_ai_security_summary(self, settings: dict | None = None, scope: str = "all") -> dict:
        ...

    def list_recent_events(self) -> list[dict]:
        ...

    def list_alerts(self) -> list[dict]:
        ...

    def list_reports(self) -> list[dict]:
        ...

    def list_incidents(self) -> list[dict]:
        ...

    def threat_timeline(self) -> list[dict]:
        ...
